version: '2.1'
services:
  kong-database:
    image: postgres:9.4
    container_name: kong-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    volumes:
      - "db-data-kong-postgres:/var/lib/postgresql/data"
  kong-migration:
    image: kong
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up
  kong:
    image: kong:latest
    container_name: kong
    depends_on:
      - kong-database
      - kong-migration
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    restart: always
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    links:
      - kong-database
      - bookings
      - users
  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"

  gin:
    build: ./gin
    image: routingwith/gin
    container_name: gin
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: gin.local

  mux:
    build: ./mux
    image: routingwith/mux
    container_name: mux
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: mux.local

  db:
    image: mongo:3.3
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./backup:/backup:rw

  db2:
    image: postgres:9.4
    container_name: pg-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres

volumes:
  db-data-kong-postgres:
